# Source from buildah/contrib/docker/Dockerfile
FROM registry.access.redhat.com/ubi10/ubi@sha256:937cb57b9dead25a68ca3b40f40db874dcf7b97dd0b438aca32c54e26220b415
RUN dnf -y update && dnf -y clean all
RUN dnf -y install containers-common golang gpgme-devel libassuan-devel libseccomp-devel make net-tools shadow-utils glibc-static && dnf -y clean all
COPY buildah/ /go/src/github.com/containers/buildah
RUN env GOPATH=/go make -C /go/src/github.com/containers/buildah clean all install
RUN sed -i -r -e 's,driver = ".*",driver = "vfs",g' /etc/containers/storage.conf
ENV BUILDAH_ISOLATION chroot
WORKDIR /root
CMD /bin/bash