# Instead of producing an image that only runs buildah, create an image which allows buildah to be called
# This will eventually reference a released image in quay.io/konflux-ci/buildah:latest but we want to
#   pin to the latest pre-release version of buildah
FROM quay.io/redhat-user-workloads/rhtap-build-tenant/buildah-container/buildah@sha256:7d7658b12457107d171f3c1644850e22a22513668484c5e971e6a773542461db as buildah-image
FROM registry.access.redhat.com/ubi9/buildah:latest
COPY --from=buildah-image /usr/bin/buildah /usr/bin/buildah