# Instead of producing an image that runs buildah, create an image which allows buildah to be called
FROM quay.io/konflux-ci/buildah:latest@sha256:8e4b00a616ec6c5762a75fa75510c1689f09e3e9db2368dccefc938c81f0ac07
USER 0
WORKDIR /
ENTRYPOINT ["/bin/bash"]