apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/buildah-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" &&
      (".tekton/build-pipeline.yaml".pathChanged() ||
      ".tekton/buildah-task-pull-request.yaml".pathChanged() ||
      ".tekton/buildah-task-push.yaml".pathChanged() ||
      "Containerfile.task".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: buildah-container
    appstudio.openshift.io/component: buildah-task
    pipelines.appstudio.openshift.io/type: build
  name: buildah-task-on-pull-request
  namespace: rhtap-build-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtap-build-tenant/buildah-container/buildah-task:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile.task
  - name: enable-amd64-build
    value: "true"
  - name: enable-arm64-build
    value: "true"
  - name: enable-ppc64le-build
    value: "true"
  - name: enable-s390x-build
    value: "true"
  pipelineRef:
    name: build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
