apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/buildah-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      ("dockerfile-json".pathChanged() ||
      "Containerfile.task".pathChanged() ||
      "scripts/**".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: buildah-container
    appstudio.openshift.io/component: buildah-task
    pipelines.appstudio.openshift.io/type: build
  name: buildah-task-on-push
  namespace: rhtap-build-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtap-build-tenant/buildah-container/buildah-task:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: Containerfile.task
  pipelineRef:
    name: build-pipeline
  timeouts:
    pipeline: "2h0m0s"
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
