apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
    tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:90dda596d44b3f861889da2fba161dff34c6116fe76c3989e3f84262ea0f29cd
        - name: kind
          value: task
      params:
      - name: image-url
        value: "$(params.output-image)"
      - name: rebuild
        value: "$(params.rebuild)"
      - name: skip-checks
        value: "$(params.skip-checks)"
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:f72fcca6732516339d55ac5f01660e287968e64e857a40a8608db27e298b5126
        - name: kind
          value: task
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      runAfter:
      - init
      params:
      - name: url
        value: "$(params.git-url)"
      - name: revision
        value: "$(params.revision)"
      - name: ociStorage
        value: "$(params.output-image).git"
      - name: ociArtifactExpiresAfter
        value: "$(params.image-expires-after)"
      workspaces:
      - name: basic-auth
        workspace: git-auth
    - name: prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: prefetch-dependencies-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.1@sha256:994f816e36ac832f4020647afd69223a015c84c503f925013c573fed52f05420
        - name: kind
          value: task
      params:
      - name: input
        value: "$(params.prefetch-input)"
      - name: hermetic
        value: "$(params.hermetic)"
      - name: dev-package-managers
        value: $(params.prefetch-dev-package-managers-enabled)
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      - name: ociStorage
        value: $(params.output-image).prefetch
      - name: ociArtifactExpiresAfter
        value: $(params.image-expires-after)
    - name: build-container-amd64
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: buildah-remote-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:a6299007879d8356a390ec1d99a2e5988d4eb2376c03472f99c55c369a13e749
        - name: kind
          value: task
      runAfter:
        - prefetch-dependencies
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      - input: "$(params.enable-amd64-build)"
        operator: in
        values:
        - 'true'
      params:
      - name: IMAGE
        value: "$(params.output-image)-amd64"
      - name: DOCKERFILE
        value: "$(params.dockerfile)"
      - name: CONTEXT
        value: "$(params.path-context)"
      - name: HERMETIC
        value: "$(params.hermetic)"
      - name: PREFETCH_INPUT
        value: "$(params.prefetch-input)"
      - name: IMAGE_EXPIRES_AFTER
        value: "$(params.image-expires-after)"
      - name: COMMIT_SHA
        value: "$(tasks.clone-repository.results.commit)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      - name: BUILD_ARGS_FILE
        value: $(params.build-args-file)
      - name: PLATFORM
        value: $(params.amd64-platform)
    - name: build-container-arm64
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: buildah-remote-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:a6299007879d8356a390ec1d99a2e5988d4eb2376c03472f99c55c369a13e749
        - name: kind
          value: task
      runAfter:
        - prefetch-dependencies
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      - input: "$(params.enable-arm64-build)"
        operator: in
        values:
        - 'true'
      params:
      - name: IMAGE
        value: "$(params.output-image)-arm64"
      - name: DOCKERFILE
        value: "$(params.dockerfile)"
      - name: CONTEXT
        value: "$(params.path-context)"
      - name: HERMETIC
        value: "$(params.hermetic)"
      - name: PREFETCH_INPUT
        value: "$(params.prefetch-input)"
      - name: IMAGE_EXPIRES_AFTER
        value: "$(params.image-expires-after)"
      - name: COMMIT_SHA
        value: "$(tasks.clone-repository.results.commit)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      - name: BUILD_ARGS_FILE
        value: $(params.build-args-file)
      - name: PLATFORM
        value: $(params.arm64-platform)
    - name: build-container-ppc64le
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: buildah-remote-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:a6299007879d8356a390ec1d99a2e5988d4eb2376c03472f99c55c369a13e749
        - name: kind
          value: task
      runAfter:
        - prefetch-dependencies
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      - input: "$(params.enable-ppc64le-build)"
        operator: in
        values:
        - 'true'
      params:
      - name: IMAGE
        value: "$(params.output-image)-ppc64le"
      - name: DOCKERFILE
        value: "$(params.dockerfile)"
      - name: CONTEXT
        value: "$(params.path-context)"
      - name: HERMETIC
        value: "$(params.hermetic)"
      - name: PREFETCH_INPUT
        value: "$(params.prefetch-input)"
      - name: IMAGE_EXPIRES_AFTER
        value: "$(params.image-expires-after)"
      - name: COMMIT_SHA
        value: "$(tasks.clone-repository.results.commit)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      - name: BUILD_ARGS_FILE
        value: $(params.build-args-file)
      - name: PLATFORM
        value: $(params.ppc64le-platform)
    - name: build-container-s390x
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: buildah-remote-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:a6299007879d8356a390ec1d99a2e5988d4eb2376c03472f99c55c369a13e749
        - name: kind
          value: task
      runAfter:
        - prefetch-dependencies
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      - input: "$(params.enable-s390x-build)"
        operator: in
        values:
        - 'true'
      params:
      - name: IMAGE
        value: "$(params.output-image)-s390x"
      - name: DOCKERFILE
        value: "$(params.dockerfile)"
      - name: CONTEXT
        value: "$(params.path-context)"
      - name: HERMETIC
        value: "$(params.hermetic)"
      - name: PREFETCH_INPUT
        value: "$(params.prefetch-input)"
      - name: IMAGE_EXPIRES_AFTER
        value: "$(params.image-expires-after)"
      - name: COMMIT_SHA
        value: "$(tasks.clone-repository.results.commit)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      - name: BUILD_ARGS_FILE
        value: $(params.build-args-file)
      - name: PLATFORM
        value: $(params.s390x-platform)
    - name: build-image-index
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: IMAGES
          value:
            - $(tasks.build-container-amd64.results.IMAGE_URL)@$(tasks.build-container-amd64.results.IMAGE_DIGEST)
            - $(tasks.build-container-arm64.results.IMAGE_URL)@$(tasks.build-container-arm64.results.IMAGE_DIGEST)
            - $(tasks.build-container-s390x.results.IMAGE_URL)@$(tasks.build-container-s390x.results.IMAGE_DIGEST)
            - $(tasks.build-container-ppc64le.results.IMAGE_URL)@$(tasks.build-container-ppc64le.results.IMAGE_DIGEST)
      runAfter:
        - build-container-amd64
        - build-container-arm64
        - build-container-s390x
        - build-container-ppc64le
      taskRef:
        params:
          - name: name
            value: build-image-manifest
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-manifest:0.1@sha256:db41e6bf0917f4d4be64d21eef2385dc329d18e93bcc834745e6342f87febc81
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
    - name: build-source-image
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: source-build-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.1@sha256:75e882bf1619dd45a4043060ce42a6ad3ce781264ade5b7f66a1d994ee159126
        - name: kind
          value: task
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      - input: "$(params.build-source-image)"
        operator: in
        values:
        - 'true'
      runAfter:
      - build-image-index
      params:
      - name: BINARY_IMAGE
        value: "$(params.output-image)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: deprecated-base-image-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: deprecated-image-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.4@sha256:f8efb0b22692fad908a1a75f8d5c0b6ed3b0bcd2a9853577e7be275e5bac1bb8
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-image-index
      params:
      - name: IMAGE_URL
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: clair-scan
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clair-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:e428b37d253621365ffb24d4053e5f3141988ae6a30fce1c8ba73b7211396eb0
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-image-index
      params:
      - name: image-digest
        value: "$(tasks.build-image-index.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-image-index.results.IMAGE_URL)"
    - name: ecosystem-cert-preflight-checks
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: ecosystem-cert-preflight-checks
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.1@sha256:df8a25a3431a70544172ed4844f9d0c6229d39130633960729f825a031a7dea9
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-image-index
      params:
      - name: image-url
        value: "$(tasks.build-image-index.results.IMAGE_URL)"
    - name: sast-snyk-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: sast-snyk-check-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.3@sha256:6d232347739a0366dcfc4e40afbcb5d1937dd3fea8952afb1bd6a4b0c5d1c1f5
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-image-index
      params:
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: image-digest
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: clamav-scan
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clamav-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.2@sha256:d78221853f7ff2befc6669dd0eeb91e6611ae84ac7754150ea0f071d92ff41cb
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-image-index
      params:
      - name: image-digest
        value: "$(tasks.build-image-index.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-image-index.results.IMAGE_URL)"
    - name: apply-tags
      params:
      - name: IMAGE
        value: $(tasks.build-image-index.results.IMAGE_URL)
      runAfter:
      - build-image-index
      taskRef:
        params:
        - name: name
          value: apply-tags
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:2c2d88c07623b2d25163994ded6e9f29205ea5bbab090f4c86379739940028b9
        - name: kind
          value: task
        resolver: bundles
    - name: rpms-signature-scan
      params:
        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: rpms-signature-scan
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:39cd56ffa26ff5edfd5bf9b61e902cae35a345c078cd9dcbc0737d30f3ce5ef1
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    params:
    - name: git-url
      type: string
      description: Source Repository URL
    - name: revision
      type: string
      description: Revision of the Source Repository
      default: ''
    - name: output-image
      type: string
      description: Fully Qualified Output Image
    - name: path-context
      type: string
      description: Path to the source code of an application's component from where to
        build image.
      default: "."
    - name: dockerfile
      type: string
      description: Path to the Dockerfile inside the context specified by parameter path-context
      default: Dockerfile
    - name: rebuild
      type: string
      description: Force rebuild image
      default: 'false'
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ''
      # default: '{"packages": [{"type": "gomod", "path": "buildah"}], "flags": ["gomod-vendor-check"]}' # fails due to https://issues.redhat.com/browse/KFLUXBUGS-1421
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: "true"
      description: Enable dev-package-managers in prefetch task
      name: prefetch-dev-package-managers-enabled
      type: string
    - name: java
      type: string
      description: Java build
      default: 'false'
    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h,
        2d, 3w for hours, days, and weeks, respectively.
      default: ''
    - name: build-source-image
      type: string
      description: Build a source image.
      default: 'false'
    - name: build-args-file
      type: string
      description: Path to a file with build arguments, see https://www.mankier.com/1/buildah-build#--build-arg-file
      default: ""
    - name: enable-amd64-build
      type: string
      description: Enable amd64 builds
      default: "true"
    - name: enable-arm64-build
      type: string
      description: Enable arm64 builds
      default: "false"
    - name: enable-ppc64le-build
      type: string
      description: Enable ppc64le builds
      default: "false"
    - name: enable-s390x-build
      type: string
      description: Enable s390x builds
      default: "false"
    - name: amd64-platform
      type: string
      description: Enable the amd64 platform to be changed from the PipelineRun file
      default: linux/amd64
    - name: arm64-platform
      type: string
      description: Enable the arm64 platform to be changed from the PipelineRun file
      default: linux/arm64
    - name: ppc64le-platform
      type: string
      description: Enable the ppc64le platform to be changed from the PipelineRun file
      default: linux/ppc64le
    - name: s390x-platform
      type: string
      description: Enable the s390x platform to be changed from the PipelineRun file
      default: linux/s390x
    workspaces:
    - name: git-auth
      optional: true
    results:
    - name: IMAGE_URL
      description: ''
      value: "$(tasks.build-image-index.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      description: ''
      value: "$(tasks.build-image-index.results.IMAGE_DIGEST)"
    - name: CHAINS-GIT_URL
      description: ''
      value: "$(tasks.clone-repository.results.url)"
    - name: CHAINS-GIT_COMMIT
      description: ''
      value: "$(tasks.clone-repository.results.commit)"
    - name: JAVA_COMMUNITY_DEPENDENCIES
      description: ''
      value: "$(tasks.build-container-amd64.results.JAVA_COMMUNITY_DEPENDENCIES)"
    finally:
    - name: show-sbom
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: show-sbom
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:945a7c9066d3e0a95d3fddb7e8a6992e4d632a2a75d8f3a9bd2ff2fef0ec9aa0
        - name: kind
          value: task
      params:
      - name: IMAGE_URL
        value: "$(tasks.build-image-index.results.IMAGE_URL)"
    - name: show-summary
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: summary
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:870d9a04d9784840a90b7bf6817cd0d0c4edfcda04b1ba1868cae625a3c3bfcc
        - name: kind
          value: task
      params:
      - name: pipelinerun-name
        value: "$(context.pipelineRun.name)"
      - name: git-url
        value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
      - name: image-url
        value: "$(params.output-image)"
      - name: build-task-status
        value: "$(tasks.build-image-index.status)"
